name: digital
version: 1.0.0+1
publish_to: none
description: A digital app.
environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  http: 0.13.4
  dio: 4.0.6
  intl: 0.17.0
  flutter_native_splash: 2.1.6
  firebase: 9.0.2
  cloud_firestore: 3.1.13
  loader_overlay: 2.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_launcher_icons: 0.9.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

