name: digital
version: 1.0.0+1
publish_to: none
description: A digital app.
environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.3
  get: 4.6.1
  http: 0.13.4
  dio: 4.0.6
  intl: 0.17.0
  flutter_native_splash: 2.1.6
  firebase: 9.0.2
  cloud_firestore: 3.1.13
  loader_overlay: 2.0.6
  font_awesome_flutter: 10.1.0
  awesome_notifications: 0.6.21

  # Base Dependencies
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  google_fonts: ^2.0.0

  # Icons
  material_design_icons_flutter: 5.0.5955-rc.1
  flutter_feather_icons: ^2.0.0+1

  #(Syncfusion Flutter packages - Charts, Calendar, ETC.)
  syncfusion_flutter_core: ^19.4.38
  syncfusion_flutter_calendar: ^19.4.38
  syncfusion_flutter_datepicker: ^19.4.38
  syncfusion_flutter_sliders: ^19.4.38
  syncfusion_flutter_charts: ^19.4.38
  syncfusion_flutter_gauges: ^19.4.38

  # Other
  google_maps_flutter: ^2.0.3
  shimmer: ^2.0.0
  url_launcher: ^6.0.3


  flutter:
    sdk: flutter
  flutx:
    path: ../flutx

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_launcher_icons: 0.9.2
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/apps/muvi/
    - lib/apps/muvi/data/
  uses-material-design: true
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages